/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlth.java;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Thanh
 */
public class pn_qlhs extends javax.swing.JFrame {

    /**
     * Creates new form pn_qlhs
     */
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    private static int state = 0;
    private ImageIcon format = null;
    //strin filename
    String filename = null;
    byte[] person_image = null;

    private String gender;

    public pn_qlhs() {
        try {
            initComponents();
            conn = db.java_db();
            Toolkit toolkit = getToolkit();
            Dimension size = toolkit.getScreenSize();
            setLocation(size.width / 2 - getWidth() / 2,
                    size.height / 2 - getHeight() / 2);
            String sql = "select * from HocSinh";
            Update_table3(sql);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(QLTK.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void Update_table3(String sql) {
        try {
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            tbl_3.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        } finally {

            try {
                rs.close();
                pst.close();

            } catch (SQLException e) {

            }
        }
    }

    private void setLuu(boolean bol) {
        btnHuy.setEnabled(bol);
        btnLuu.setEnabled(bol);
        btnThem.setEnabled(!bol);
        btnXoa.setEnabled(!bol);
        btnSua.setEnabled(!bol);

        txt_mahs.setText("");
        txt_malop.setText("");
        txt_diachi.setText("");
        txt_hoten.setText("");
        txt_sdt.setText("");
        txt_ngaysinh.setText("");

        /*txtMatKhau.setEditable(bol);
        txtQuyen.setEditable(bol);
        txtTaiKhoan.setEditable(bol);*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_mahs = new javax.swing.JTextField();
        txt_hoten = new javax.swing.JTextField();
        txt_ngaysinh = new javax.swing.JTextField();
        txt_sdt = new javax.swing.JTextField();
        txt_diachi = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_timhs = new javax.swing.JTextField();
        btn_timhs = new javax.swing.JButton();
        chb_nam = new javax.swing.JCheckBox();
        chb_nu = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        txt_malop = new javax.swing.JTextField();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        img = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_3 = new javax.swing.JTable();
        btnHuy = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Mã học sinh :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel2.setText("Họ và tên :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel3.setText("Giới tính :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel4.setText("Ngày sinh :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel5.setText("SĐT(PH) :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jLabel6.setText("Hình ảnh :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));

        jLabel7.setText("Địa chỉ :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, 20));

        txt_mahs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_mahsActionPerformed(evt);
            }
        });
        jPanel1.add(txt_mahs, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 160, -1));

        txt_hoten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hotenActionPerformed(evt);
            }
        });
        jPanel1.add(txt_hoten, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 160, -1));

        txt_ngaysinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ngaysinhActionPerformed(evt);
            }
        });
        jPanel1.add(txt_ngaysinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 170, -1));
        jPanel1.add(txt_sdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 170, -1));
        jPanel1.add(txt_diachi, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 170, 20));

        jLabel8.setText("Tìm học sinh:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, -1, 20));

        txt_timhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_timhsActionPerformed(evt);
            }
        });
        jPanel1.add(txt_timhs, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, 220, -1));

        btn_timhs.setText("dowjdj");
        btn_timhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timhsActionPerformed(evt);
            }
        });
        jPanel1.add(btn_timhs, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 160, -1, -1));

        chb_nam.setText("Nam");
        chb_nam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chb_namActionPerformed(evt);
            }
        });
        jPanel1.add(chb_nam, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        chb_nu.setText("Nữ");
        chb_nu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chb_nuActionPerformed(evt);
            }
        });
        jPanel1.add(chb_nu, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, -1, -1));

        jLabel9.setText("Mã lớp :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));
        jPanel1.add(txt_malop, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 170, -1));

        jDesktopPane1.setLayer(img, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(img, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(img, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 160, 110));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel10.setText("QUẢN LÝ HỌC SINH");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 390, 50));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách tài khoản", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Adobe Arabic", 1, 14))); // NOI18N

        tbl_3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tbl_3);

        btnHuy.setText("Hủy bỏ");
        btnHuy.setEnabled(false);
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnLuu.setText("Lưu");
        btnLuu.setEnabled(false);
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXoa)
                    .addComponent(btnSua)
                    .addComponent(btnThem)
                    .addComponent(btnLuu)
                    .addComponent(btnHuy))
                .addContainerGap())
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, -1, -1));

        jMenu1.setText("Nâng cao");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/attach.png"))); // NOI18N
        jMenuItem1.setText("Thêm ảnh");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Giúp đỡ");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("Ver 1.0");
        jMenu2.add(jCheckBoxMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 958, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_mahsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_mahsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_mahsActionPerformed

    private void txt_timhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_timhsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_timhsActionPerformed

    private void txt_hotenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hotenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hotenActionPerformed

    private void txt_ngaysinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ngaysinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ngaysinhActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();

        filename = f.getAbsolutePath();
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(img.getWidth(), img.getHeight(), Image.SCALE_DEFAULT));
        img.setIcon(imageIcon);
        try {

            File image = new File(filename);
            FileInputStream fis = new FileInputStream(image);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte[] buf = new byte[1024];

            for (int readNum; (readNum = fis.read(buf)) != -1;) {

                bos.write(buf, 0, readNum);
            }
            person_image = bos.toByteArray();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, e);

        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void chb_namActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chb_namActionPerformed
        // TODO add your handling code here:
        chb_nam.setSelected(true);
        chb_nu.setSelected(false);
        gender = "Nam";
    }//GEN-LAST:event_chb_namActionPerformed

    private void chb_nuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chb_nuActionPerformed
        // TODO add your handling code here:
        chb_nam.setSelected(!true);
        chb_nu.setSelected(!false);
        gender = "Nữ";
    }//GEN-LAST:event_chb_nuActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        setLuu(false);
    }//GEN-LAST:event_btnHuyActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int row = tbl_3.getSelectedRow();
        if (row >= 0) {
            try {
                setLuu(true);
                txt_mahs.setText(tbl_3.getModel().getValueAt(row, 0).toString());
                txt_hoten.setText(tbl_3.getModel().getValueAt(row, 1).toString());
                txt_ngaysinh.setText(tbl_3.getModel().getValueAt(row, 2).toString());
                txt_sdt.setText(tbl_3.getModel().getValueAt(row, 3).toString());
                txt_malop.setText(tbl_3.getModel().getValueAt(row, 4).toString());
                txt_diachi.setText(tbl_3.getModel().getValueAt(row, 5).toString());
                String sql = "delete from HocSinh where MaHS =?";
                pst = conn.prepareStatement(sql);
                pst.setString(1, txt_mahs.getText());
                pst.executeUpdate();
                Update_table3("select * from HocSinh");
                setLuu(false);
                JOptionPane.showMessageDialog(null, "Thao tác thành công!");
            } catch (SQLException ex) {
                Logger.getLogger(QLTK.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        //SetLuu(true);*/
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        int row = tbl_3.getSelectedRow();
        if (row >= 0) {
            setLuu(true);
            txt_mahs.setText(tbl_3.getModel().getValueAt(row, 0).toString());
            txt_hoten.setText(tbl_3.getModel().getValueAt(row, 1).toString());
            txt_ngaysinh.setText(tbl_3.getModel().getValueAt(row, 2).toString());
            txt_sdt.setText(tbl_3.getModel().getValueAt(row, 3).toString());
            txt_malop.setText(tbl_3.getModel().getValueAt(row, 5).toString());
            txt_diachi.setText(tbl_3.getModel().getValueAt(row, 4).toString());
            state = 3;
        }

    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        setLuu(true);
        state = 1;
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:

        if (state == 3) {
            String sql = "update HocSinh set TenHS = ?, GioiTinh = ?, SDT = ?, DiaChi = ?, MaLop = ?, NgaySinh = ? , HinhAnh = ? where MaHS =?";
            try {
                pst = conn.prepareStatement(sql);
                pst.setString(1, txt_mahs.getText());
                pst.setString(2, txt_hoten.getText());
                pst.setString(3, gender);
                pst.setString(4, txt_ngaysinh.getText());
                pst.setString(5, txt_sdt.getText());
                pst.setString(6, txt_malop.getText());
                pst.setString(7, txt_diachi.getText());

                pst.executeUpdate();
                Update_table3("select * from HocSinh");
                setLuu(false);
                JOptionPane.showMessageDialog(null, "Sửa thành công!");
            } catch (SQLException ex) {
                Logger.getLogger(QLTK.class.getName()).log(Level.SEVERE, null, ex);
            }
            state = 0;
        }
        if (state == 1) {
            String sql = "insert into HocSinh(TenHS,GioiTinh,SDT,DiaChi,MaLop,NgaySinh,HinhAnh) values(?,?,?,?,?,?,?)";
            try {
                pst = conn.prepareStatement(sql);
                pst.setString(1, txt_hoten.getText());
                pst.setString(2, gender);
                pst.setString(3, txt_sdt.getText());
                pst.setString(4, txt_diachi.getText());
                pst.setString(5, txt_malop.getText());
                pst.setString(6, txt_ngaysinh.getText());
                pst.setBytes(7,person_image);
                pst.executeUpdate();
                Update_table3("select * from HocSinh");
                setLuu(false);
                JOptionPane.showMessageDialog(null, "Thêm thành công!");
            } catch (SQLException ex) {
                Logger.getLogger(QLTK.class.getName()).log(Level.SEVERE, null, ex);
            }
            state = 0;
        }

    }//GEN-LAST:event_btnLuuActionPerformed

    private void btn_timhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timhsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_timhsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pn_qlhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pn_qlhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pn_qlhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pn_qlhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pn_qlhs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btn_timhs;
    private javax.swing.JCheckBox chb_nam;
    private javax.swing.JCheckBox chb_nu;
    private javax.swing.JLabel img;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tbl_3;
    private javax.swing.JTextField txt_diachi;
    private javax.swing.JTextField txt_hoten;
    private javax.swing.JTextField txt_mahs;
    private javax.swing.JTextField txt_malop;
    private javax.swing.JTextField txt_ngaysinh;
    private javax.swing.JTextField txt_sdt;
    private javax.swing.JTextField txt_timhs;
    // End of variables declaration//GEN-END:variables
}
